export type SupportedLocale = (typeof supportedLocales)[number];

export type MajorCityLocation = {
  id: string;
  name: string;
  admin1: string;
  country: string;
  latitude: number;
  longitude: number;
  timezone: string;
};

export type WeatherConditionKind =
  | "clear-day"
  | "clear-night"
  | "partly-cloudy"
  | "cloudy"
  | "fog"
  | "drizzle"
  | "rain"
  | "snow"
  | "storm"
  | "unknown";

export type WeatherCondition = {
  kind: WeatherConditionKind;
  symbol: string;
  label: string;
};

export type TemperatureDay = {
  temperature_min: number;
  temperature_max: number;
};

export type TemperatureRangeClasses = {
  startClass: string;
  widthClass: string;
  currentClass: string | undefined;
};

export const supportedLocales = [
  "en-US",
  "zh-CN",
  "zh-TW",
  "ja-JP",
  "ko-KR",
  "de-DE",
  "fr-FR",
  "es-ES",
  "pt-BR",
  "ru-RU",
] as const;
const translations = {
  "en-US": {
    chooseLocation: "Choose location",
    majorCities: "Major cities",
    closeLocationPicker: "Close location picker",
    searchPlaceholder: "Search city or place",
    search: "Search",
    searchHint: "Search for a city to see its local time and ten-day outlook.",
    favorites: "Recent locations",
    remove: "Remove",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    feelsLike: "Feels like",
    humidity: "Humidity",
    wind: "Wind",
    precipitation: "Precipitation",
    detailsLabel: "Current weather details",
    forecastTitle: "10-day forecast",
    forecastLabel: "Ten-day forecast",
    secureBroker: "Redeven secure network broker",
    today: "Today",
    tonight: "Tonight",
    high: "High",
    low: "Low",
    poweredBy: "Weather data by Open-Meteo.com · CC BY 4.0",
    searching: "Finding places…",
    noResults: "No matching places found.",
    loading: "Loading your weather…",
    loadingLocation: "Loading weather for {city}…",
    onboardingTitle: "Choose a city to begin",
    onboardingBody:
      "Search a place or choose a major city below for local time, current conditions, and the ten-day forecast.",
    refreshFailed: "Showing saved weather; the latest update is unavailable.",
    permission:
      "Network access is required to load live weather. Grant the plugin’s network permission, then try again.",
    unavailable:
      "Live weather is unavailable right now. Your recent locations are still available.",
    searchError: "Place search is unavailable right now.",
    conditions: {
      "clear-day": "Clear sky",
      "clear-night": "Clear sky",
      "partly-cloudy": "Partly cloudy",
      cloudy: "Cloudy",
      fog: "Fog",
      drizzle: "Drizzle",
      rain: "Rain",
      snow: "Snow",
      storm: "Thunderstorm",
      unknown: "Conditions unavailable",
    },
    weather: "Weather",
    hideSidebar: "Hide sidebar",
    toggleSidebar: "Toggle sidebar",
    savedWeather: "Saved forecast",
    observed: "Observed",
    hourly: "Hourly forecast",
    now: "Now",
    daysForecast: "{count}-day forecast",
    gusts: "Gusts {speed}",
    actualTemperature: "Actual temperature: {temperature}",
    currentWind: "Current wind speed",
    relativeHumidity: "Relative humidity",
    sunset: "Sunset",
    sunrise: "Sunrise",
    precipitationTotal: "Precipitation",
    chanceToday: "Today · {chance} chance of rain",
    uv: "UV index",
    lowUV: "Low",
    moderateUV: "Moderate",
    highUV: "High",
    veryHighUV: "Very high",
    visibility: "Visibility",
    horizontalVisibility: "Horizontal visibility",
    pressure: "Pressure",
    seaLevel: "hPa · Sea level",
    north: "N",
    west: "W",
    east: "E",
    south: "S",
    conditionsTitle: "Weather conditions",
    closeDetails: "Close details",
    dailyRange: "Daily range",
    missingHours:
      "Hourly details are unavailable for this saved forecast. Refresh to try again.",
    temperatureType: "Temperature type",
    actual: "Actual",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "zh-CN": {
    chooseLocation: "选择城市",
    majorCities: "全球主要城市",
    closeLocationPicker: "关闭城市选择",
    searchPlaceholder: "搜索城市或地区",
    search: "搜索",
    searchHint: "搜索城市，查看当地时间和未来十天天气。",
    favorites: "最近地点",
    remove: "移除",
    refresh: "刷新",
    refreshing: "正在刷新…",
    feelsLike: "体感温度",
    humidity: "湿度",
    wind: "风速",
    precipitation: "降水",
    detailsLabel: "当前天气详情",
    forecastTitle: "10日天气预报",
    forecastLabel: "未来十天天气预报",
    secureBroker: "由 Redeven 安全网络代理访问",
    today: "今天",
    tonight: "今晚",
    high: "最高",
    low: "最低",
    poweredBy: "天气数据由 Open-Meteo.com 提供 · CC BY 4.0",
    searching: "正在查找地点…",
    noResults: "没有找到匹配地点。",
    loading: "正在加载天气…",
    loadingLocation: "正在加载{city}天气…",
    onboardingTitle: "先选择一个城市",
    onboardingBody:
      "搜索地点或从下方常用城市中选择，立即查看当地时间、实时天气和未来十天趋势。",
    refreshFailed: "正在显示缓存天气，暂时无法获取最新数据。",
    permission: "加载实时天气需要网络权限。授权后请重试。",
    unavailable: "暂时无法获取实时天气，你仍可查看最近地点。",
    searchError: "暂时无法搜索地点。",
    conditions: {
      "clear-day": "晴",
      "clear-night": "晴",
      "partly-cloudy": "多云间晴",
      cloudy: "多云",
      fog: "有雾",
      drizzle: "小雨",
      rain: "有雨",
      snow: "有雪",
      storm: "雷暴",
      unknown: "暂无天气信息",
    },
    weather: "天气",
    hideSidebar: "隐藏边栏",
    toggleSidebar: "显示或隐藏边栏",
    savedWeather: "缓存预报",
    observed: "观测时间",
    hourly: "每小时天气预报",
    now: "现在",
    daysForecast: "{count}日天气预报",
    gusts: "阵风 {speed}",
    actualTemperature: "实际气温：{temperature}",
    currentWind: "当前风速",
    relativeHumidity: "当前相对湿度",
    sunset: "日落",
    sunrise: "日出",
    precipitationTotal: "降水",
    chanceToday: "今天 · 降水概率 {chance}",
    uv: "紫外线指数",
    lowUV: "低",
    moderateUV: "中等",
    highUV: "高",
    veryHighUV: "很高",
    visibility: "能见度",
    horizontalVisibility: "水平方向能见度",
    pressure: "气压",
    seaLevel: "百帕 · 海平面气压",
    north: "北",
    west: "西",
    east: "东",
    south: "南",
    conditionsTitle: "天气状况",
    closeDetails: "关闭详情",
    dailyRange: "全天范围",
    missingHours: "此缓存预报暂无逐小时详情，请刷新后重试。",
    temperatureType: "气温类型",
    actual: "实际气温",
    millimeters: "毫米",
    kilometers: "公里",
    windUnit: "公里/时",
  },
  "zh-TW": {
    chooseLocation: "選擇城市",
    majorCities: "全球主要城市",
    closeLocationPicker: "關閉城市選擇",
    searchPlaceholder: "搜尋城市或地區",
    search: "搜尋",
    searchHint: "搜尋城市，查看當地時間和未來十天天氣。",
    favorites: "最近地點",
    remove: "移除",
    refresh: "重新整理",
    refreshing: "正在重新整理…",
    feelsLike: "體感溫度",
    humidity: "濕度",
    wind: "風速",
    precipitation: "降水",
    detailsLabel: "目前天氣詳情",
    forecastTitle: "10日天氣預報",
    forecastLabel: "未來十天天氣預報",
    secureBroker: "Redeven 安全網路代理",
    today: "今天",
    tonight: "今晚",
    high: "最高",
    low: "最低",
    poweredBy: "天氣資料由 Open-Meteo.com 提供 · CC BY 4.0",
    searching: "正在搜尋地點…",
    noResults: "找不到符合的地點。",
    loading: "正在載入天氣…",
    loadingLocation: "正在載入{city}天氣…",
    onboardingTitle: "先選擇一個城市",
    onboardingBody:
      "搜尋地點或選擇下方城市，查看當地時間、即時天氣和未來十天預報。",
    refreshFailed: "正在顯示快取天氣，暫時無法取得最新資料。",
    permission: "載入即時天氣需要網路權限。授權後請重試。",
    unavailable: "暫時無法取得即時天氣，仍可查看最近地點。",
    searchError: "暫時無法搜尋地點。",
    conditions: {
      "clear-day": "晴",
      "clear-night": "晴",
      "partly-cloudy": "晴時多雲",
      cloudy: "多雲",
      fog: "有霧",
      drizzle: "毛毛雨",
      rain: "有雨",
      snow: "有雪",
      storm: "雷雨",
      unknown: "暫無天氣資訊",
    },
    weather: "天氣",
    hideSidebar: "隱藏側邊欄",
    toggleSidebar: "顯示或隱藏側邊欄",
    savedWeather: "快取預報",
    observed: "觀測時間",
    hourly: "每小時天氣預報",
    now: "現在",
    daysForecast: "{count}日天氣預報",
    gusts: "陣風 {speed}",
    actualTemperature: "實際氣溫：{temperature}",
    currentWind: "目前風速",
    relativeHumidity: "目前相對濕度",
    sunset: "日落",
    sunrise: "日出",
    precipitationTotal: "降水",
    chanceToday: "今天 · 降水機率 {chance}",
    uv: "紫外線指數",
    lowUV: "低",
    moderateUV: "中等",
    highUV: "高",
    veryHighUV: "很高",
    visibility: "能見度",
    horizontalVisibility: "水平方向能見度",
    pressure: "氣壓",
    seaLevel: "百帕 · 海平面氣壓",
    north: "北",
    west: "西",
    east: "東",
    south: "南",
    conditionsTitle: "天氣狀況",
    closeDetails: "關閉詳情",
    dailyRange: "全天範圍",
    missingHours: "此快取預報暫無每小時詳情，請重新整理後重試。",
    temperatureType: "氣溫類型",
    actual: "實際氣溫",
    millimeters: "毫米",
    kilometers: "公里",
    windUnit: "公里/時",
  },
  "ja-JP": {
    chooseLocation: "都市を選択",
    majorCities: "世界の主要都市",
    closeLocationPicker: "都市の選択を閉じる",
    searchPlaceholder: "都市や地域を検索",
    search: "検索",
    searchHint: "都市を検索して、現地時刻と10日間の天気を確認できます。",
    favorites: "最近の場所",
    remove: "削除",
    refresh: "更新",
    refreshing: "更新中…",
    feelsLike: "体感温度",
    humidity: "湿度",
    wind: "風速",
    precipitation: "降水",
    detailsLabel: "現在の天気の詳細",
    forecastTitle: "10日間天気予報",
    forecastLabel: "10日間の天気予報",
    secureBroker: "Redeven の安全なネットワーク接続",
    today: "今日",
    tonight: "今夜",
    high: "最高",
    low: "最低",
    poweredBy: "気象データ：Open-Meteo.com · CC BY 4.0",
    searching: "場所を検索中…",
    noResults: "一致する場所が見つかりません。",
    loading: "天気を読み込み中…",
    loadingLocation: "{city}の天気を読み込み中…",
    onboardingTitle: "都市を選んで始めましょう",
    onboardingBody:
      "場所を検索するか、下の都市を選択すると、現地時刻、現在の天気、10日間の予報を確認できます。",
    refreshFailed: "保存済みの天気を表示しています。最新情報を取得できません。",
    permission:
      "最新の天気にはネットワーク権限が必要です。許可してから再試行してください。",
    unavailable:
      "現在、最新の天気を取得できません。最近の場所は引き続き利用できます。",
    searchError: "現在、場所を検索できません。",
    conditions: {
      "clear-day": "快晴",
      "clear-night": "快晴",
      "partly-cloudy": "晴れ時々曇り",
      cloudy: "曇り",
      fog: "霧",
      drizzle: "霧雨",
      rain: "雨",
      snow: "雪",
      storm: "雷雨",
      unknown: "天気情報なし",
    },
    weather: "天気",
    hideSidebar: "サイドバーを隠す",
    toggleSidebar: "サイドバーの表示を切り替え",
    savedWeather: "保存済みの予報",
    observed: "観測時刻",
    hourly: "1時間ごとの予報",
    now: "現在",
    daysForecast: "{count}日間天気予報",
    gusts: "突風 {speed}",
    actualTemperature: "実際の気温：{temperature}",
    currentWind: "現在の風速",
    relativeHumidity: "相対湿度",
    sunset: "日の入り",
    sunrise: "日の出",
    precipitationTotal: "降水量",
    chanceToday: "今日 · 降水確率 {chance}",
    uv: "UV指数",
    lowUV: "低い",
    moderateUV: "中程度",
    highUV: "高い",
    veryHighUV: "非常に高い",
    visibility: "視程",
    horizontalVisibility: "水平方向の視程",
    pressure: "気圧",
    seaLevel: "hPa · 海面気圧",
    north: "北",
    west: "西",
    east: "東",
    south: "南",
    conditionsTitle: "天気の状況",
    closeDetails: "詳細を閉じる",
    dailyRange: "1日の範囲",
    missingHours:
      "この保存済み予報には1時間ごとの詳細がありません。更新して再試行してください。",
    temperatureType: "気温の種類",
    actual: "実際の気温",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "ko-KR": {
    chooseLocation: "도시 선택",
    majorCities: "세계 주요 도시",
    closeLocationPicker: "도시 선택 닫기",
    searchPlaceholder: "도시 또는 지역 검색",
    search: "검색",
    searchHint: "도시를 검색하여 현지 시간과 10일 예보를 확인하세요.",
    favorites: "최근 위치",
    remove: "삭제",
    refresh: "새로 고침",
    refreshing: "새로 고치는 중…",
    feelsLike: "체감 온도",
    humidity: "습도",
    wind: "풍속",
    precipitation: "강수",
    detailsLabel: "현재 날씨 상세 정보",
    forecastTitle: "10일 예보",
    forecastLabel: "10일간의 날씨 예보",
    secureBroker: "Redeven 보안 네트워크 연결",
    today: "오늘",
    tonight: "오늘 밤",
    high: "최고",
    low: "최저",
    poweredBy: "날씨 데이터: Open-Meteo.com · CC BY 4.0",
    searching: "위치 검색 중…",
    noResults: "일치하는 위치가 없습니다.",
    loading: "날씨를 불러오는 중…",
    loadingLocation: "{city} 날씨를 불러오는 중…",
    onboardingTitle: "도시를 선택하여 시작하세요",
    onboardingBody:
      "위치를 검색하거나 아래 도시를 선택하여 현지 시간, 현재 날씨, 10일 예보를 확인하세요.",
    refreshFailed: "저장된 날씨를 표시합니다. 최신 정보를 가져올 수 없습니다.",
    permission:
      "실시간 날씨를 불러오려면 네트워크 권한이 필요합니다. 허용한 후 다시 시도하세요.",
    unavailable:
      "지금은 실시간 날씨를 가져올 수 없습니다. 최근 위치는 계속 사용할 수 있습니다.",
    searchError: "지금은 위치를 검색할 수 없습니다.",
    conditions: {
      "clear-day": "맑음",
      "clear-night": "맑음",
      "partly-cloudy": "구름 조금",
      cloudy: "흐림",
      fog: "안개",
      drizzle: "이슬비",
      rain: "비",
      snow: "눈",
      storm: "뇌우",
      unknown: "날씨 정보 없음",
    },
    weather: "날씨",
    hideSidebar: "사이드바 숨기기",
    toggleSidebar: "사이드바 표시 전환",
    savedWeather: "저장된 예보",
    observed: "관측 시간",
    hourly: "시간별 예보",
    now: "지금",
    daysForecast: "{count}일 예보",
    gusts: "돌풍 {speed}",
    actualTemperature: "실제 온도: {temperature}",
    currentWind: "현재 풍속",
    relativeHumidity: "상대 습도",
    sunset: "일몰",
    sunrise: "일출",
    precipitationTotal: "강수량",
    chanceToday: "오늘 · 강수 확률 {chance}",
    uv: "자외선 지수",
    lowUV: "낮음",
    moderateUV: "보통",
    highUV: "높음",
    veryHighUV: "매우 높음",
    visibility: "가시거리",
    horizontalVisibility: "수평 가시거리",
    pressure: "기압",
    seaLevel: "hPa · 해면 기압",
    north: "북",
    west: "서",
    east: "동",
    south: "남",
    conditionsTitle: "날씨 상태",
    closeDetails: "상세 정보 닫기",
    dailyRange: "일일 범위",
    missingHours:
      "저장된 예보에 시간별 상세 정보가 없습니다. 새로 고친 후 다시 시도하세요.",
    temperatureType: "온도 유형",
    actual: "실제 온도",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "de-DE": {
    chooseLocation: "Ort auswählen",
    majorCities: "Großstädte",
    closeLocationPicker: "Ortsauswahl schließen",
    searchPlaceholder: "Stadt oder Ort suchen",
    search: "Suchen",
    searchHint:
      "Suchen Sie einen Ort, um die Ortszeit und die Zehntagesvorhersage zu sehen.",
    favorites: "Letzte Orte",
    remove: "Entfernen",
    refresh: "Aktualisieren",
    refreshing: "Wird aktualisiert…",
    feelsLike: "Gefühlt",
    humidity: "Luftfeuchte",
    wind: "Wind",
    precipitation: "Niederschlag",
    detailsLabel: "Aktuelle Wetterdetails",
    forecastTitle: "10-Tage-Vorhersage",
    forecastLabel: "Wettervorhersage für zehn Tage",
    secureBroker: "Sichere Netzwerkverbindung von Redeven",
    today: "Heute",
    tonight: "Heute Nacht",
    high: "Hoch",
    low: "Tief",
    poweredBy: "Wetterdaten: Open-Meteo.com · CC BY 4.0",
    searching: "Orte werden gesucht…",
    noResults: "Keine passenden Orte gefunden.",
    loading: "Wetter wird geladen…",
    loadingLocation: "Wetter für {city} wird geladen…",
    onboardingTitle: "Wählen Sie einen Ort",
    onboardingBody:
      "Suchen Sie einen Ort oder wählen Sie eine Stadt, um Ortszeit, aktuelles Wetter und die Zehntagesvorhersage zu sehen.",
    refreshFailed:
      "Gespeichertes Wetter wird angezeigt. Die neuesten Daten sind nicht verfügbar.",
    permission:
      "Für aktuelles Wetter ist die Netzwerkberechtigung erforderlich. Erteilen Sie sie und versuchen Sie es erneut.",
    unavailable:
      "Aktuelles Wetter ist derzeit nicht verfügbar. Ihre letzten Orte bleiben verfügbar.",
    searchError: "Die Ortssuche ist derzeit nicht verfügbar.",
    conditions: {
      "clear-day": "Klar",
      "clear-night": "Klar",
      "partly-cloudy": "Teilweise bewölkt",
      cloudy: "Bewölkt",
      fog: "Nebel",
      drizzle: "Nieselregen",
      rain: "Regen",
      snow: "Schnee",
      storm: "Gewitter",
      unknown: "Keine Wetterdaten",
    },
    weather: "Wetter",
    hideSidebar: "Seitenleiste ausblenden",
    toggleSidebar: "Seitenleiste umschalten",
    savedWeather: "Gespeicherte Vorhersage",
    observed: "Beobachtet",
    hourly: "Stündliche Vorhersage",
    now: "Jetzt",
    daysForecast: "{count}-Tage-Vorhersage",
    gusts: "Böen {speed}",
    actualTemperature: "Tatsächliche Temperatur: {temperature}",
    currentWind: "Aktuelle Windgeschwindigkeit",
    relativeHumidity: "Relative Luftfeuchte",
    sunset: "Sonnenuntergang",
    sunrise: "Sonnenaufgang",
    precipitationTotal: "Niederschlag",
    chanceToday: "Heute · Regenwahrscheinlichkeit {chance}",
    uv: "UV-Index",
    lowUV: "Niedrig",
    moderateUV: "Mäßig",
    highUV: "Hoch",
    veryHighUV: "Sehr hoch",
    visibility: "Sichtweite",
    horizontalVisibility: "Horizontale Sichtweite",
    pressure: "Luftdruck",
    seaLevel: "hPa · Auf Meereshöhe",
    north: "N",
    west: "W",
    east: "O",
    south: "S",
    conditionsTitle: "Wetterbedingungen",
    closeDetails: "Details schließen",
    dailyRange: "Tagesspanne",
    missingHours:
      "Für diese gespeicherte Vorhersage fehlen stündliche Details. Bitte aktualisieren Sie die Daten.",
    temperatureType: "Temperaturtyp",
    actual: "Tatsächlich",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "fr-FR": {
    chooseLocation: "Choisir un lieu",
    majorCities: "Grandes villes",
    closeLocationPicker: "Fermer le choix du lieu",
    searchPlaceholder: "Rechercher une ville ou un lieu",
    search: "Rechercher",
    searchHint:
      "Recherchez une ville pour consulter l’heure locale et les prévisions sur dix jours.",
    favorites: "Lieux récents",
    remove: "Supprimer",
    refresh: "Actualiser",
    refreshing: "Actualisation…",
    feelsLike: "Ressenti",
    humidity: "Humidité",
    wind: "Vent",
    precipitation: "Précipitations",
    detailsLabel: "Détails météo actuels",
    forecastTitle: "Prévisions sur 10 jours",
    forecastLabel: "Prévisions météo sur dix jours",
    secureBroker: "Connexion réseau sécurisée de Redeven",
    today: "Aujourd’hui",
    tonight: "Cette nuit",
    high: "Max.",
    low: "Min.",
    poweredBy: "Données météo : Open-Meteo.com · CC BY 4.0",
    searching: "Recherche de lieux…",
    noResults: "Aucun lieu correspondant.",
    loading: "Chargement de la météo…",
    loadingLocation: "Chargement de la météo pour {city}…",
    onboardingTitle: "Choisissez une ville",
    onboardingBody:
      "Recherchez un lieu ou choisissez une ville pour consulter l’heure locale, la météo actuelle et les prévisions sur dix jours.",
    refreshFailed:
      "Les données enregistrées sont affichées. La dernière mise à jour est indisponible.",
    permission:
      "L’accès au réseau est nécessaire pour la météo en direct. Autorisez-le, puis réessayez.",
    unavailable:
      "La météo en direct est indisponible. Vos lieux récents restent accessibles.",
    searchError: "La recherche de lieux est indisponible.",
    conditions: {
      "clear-day": "Ciel dégagé",
      "clear-night": "Ciel dégagé",
      "partly-cloudy": "Partiellement nuageux",
      cloudy: "Nuageux",
      fog: "Brouillard",
      drizzle: "Bruine",
      rain: "Pluie",
      snow: "Neige",
      storm: "Orage",
      unknown: "Conditions indisponibles",
    },
    weather: "Météo",
    hideSidebar: "Masquer la barre latérale",
    toggleSidebar: "Afficher ou masquer la barre latérale",
    savedWeather: "Prévisions enregistrées",
    observed: "Observation",
    hourly: "Prévisions horaires",
    now: "Maint.",
    daysForecast: "Prévisions sur {count} jours",
    gusts: "Rafales à {speed}",
    actualTemperature: "Température réelle : {temperature}",
    currentWind: "Vitesse actuelle du vent",
    relativeHumidity: "Humidité relative",
    sunset: "Coucher du soleil",
    sunrise: "Lever du soleil",
    precipitationTotal: "Précipitations",
    chanceToday: "Aujourd’hui · Risque de pluie : {chance}",
    uv: "Indice UV",
    lowUV: "Faible",
    moderateUV: "Modéré",
    highUV: "Élevé",
    veryHighUV: "Très élevé",
    visibility: "Visibilité",
    horizontalVisibility: "Visibilité horizontale",
    pressure: "Pression",
    seaLevel: "hPa · Au niveau de la mer",
    north: "N",
    west: "O",
    east: "E",
    south: "S",
    conditionsTitle: "Conditions météo",
    closeDetails: "Fermer les détails",
    dailyRange: "Plage quotidienne",
    missingHours:
      "Les détails horaires de ces prévisions enregistrées sont indisponibles. Actualisez pour réessayer.",
    temperatureType: "Type de température",
    actual: "Réelle",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "es-ES": {
    chooseLocation: "Elegir ubicación",
    majorCities: "Ciudades principales",
    closeLocationPicker: "Cerrar selección de ubicación",
    searchPlaceholder: "Buscar ciudad o lugar",
    search: "Buscar",
    searchHint:
      "Busca una ciudad para ver la hora local y la previsión de diez días.",
    favorites: "Ubicaciones recientes",
    remove: "Eliminar",
    refresh: "Actualizar",
    refreshing: "Actualizando…",
    feelsLike: "Sensación",
    humidity: "Humedad",
    wind: "Viento",
    precipitation: "Precipitación",
    detailsLabel: "Detalles del tiempo actual",
    forecastTitle: "Previsión de 10 días",
    forecastLabel: "Previsión del tiempo de diez días",
    secureBroker: "Conexión de red segura de Redeven",
    today: "Hoy",
    tonight: "Esta noche",
    high: "Máx.",
    low: "Mín.",
    poweredBy: "Datos meteorológicos: Open-Meteo.com · CC BY 4.0",
    searching: "Buscando lugares…",
    noResults: "No se encontraron coincidencias.",
    loading: "Cargando el tiempo…",
    loadingLocation: "Cargando el tiempo de {city}…",
    onboardingTitle: "Elige una ciudad",
    onboardingBody:
      "Busca un lugar o elige una ciudad para ver la hora local, el tiempo actual y la previsión de diez días.",
    refreshFailed:
      "Se muestra el tiempo guardado. La última actualización no está disponible.",
    permission:
      "El tiempo en directo requiere permiso de red. Concédelo y vuelve a intentarlo.",
    unavailable:
      "El tiempo en directo no está disponible. Tus ubicaciones recientes siguen disponibles.",
    searchError: "La búsqueda de lugares no está disponible.",
    conditions: {
      "clear-day": "Despejado",
      "clear-night": "Despejado",
      "partly-cloudy": "Parcialmente nuboso",
      cloudy: "Nuboso",
      fog: "Niebla",
      drizzle: "Llovizna",
      rain: "Lluvia",
      snow: "Nieve",
      storm: "Tormenta",
      unknown: "Sin información del tiempo",
    },
    weather: "Tiempo",
    hideSidebar: "Ocultar barra lateral",
    toggleSidebar: "Mostrar u ocultar barra lateral",
    savedWeather: "Previsión guardada",
    observed: "Observación",
    hourly: "Previsión por horas",
    now: "Ahora",
    daysForecast: "Previsión de {count} días",
    gusts: "Rachas de {speed}",
    actualTemperature: "Temperatura real: {temperature}",
    currentWind: "Velocidad actual del viento",
    relativeHumidity: "Humedad relativa",
    sunset: "Puesta de sol",
    sunrise: "Salida del sol",
    precipitationTotal: "Precipitación",
    chanceToday: "Hoy · Probabilidad de lluvia: {chance}",
    uv: "Índice UV",
    lowUV: "Bajo",
    moderateUV: "Moderado",
    highUV: "Alto",
    veryHighUV: "Muy alto",
    visibility: "Visibilidad",
    horizontalVisibility: "Visibilidad horizontal",
    pressure: "Presión",
    seaLevel: "hPa · A nivel del mar",
    north: "N",
    west: "O",
    east: "E",
    south: "S",
    conditionsTitle: "Condiciones del tiempo",
    closeDetails: "Cerrar detalles",
    dailyRange: "Intervalo diario",
    missingHours:
      "No hay detalles por horas para esta previsión guardada. Actualiza para volver a intentarlo.",
    temperatureType: "Tipo de temperatura",
    actual: "Real",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "pt-BR": {
    chooseLocation: "Escolher local",
    majorCities: "Principais cidades",
    closeLocationPicker: "Fechar seleção de local",
    searchPlaceholder: "Buscar cidade ou local",
    search: "Buscar",
    searchHint:
      "Busque uma cidade para ver a hora local e a previsão de dez dias.",
    favorites: "Locais recentes",
    remove: "Remover",
    refresh: "Atualizar",
    refreshing: "Atualizando…",
    feelsLike: "Sensação",
    humidity: "Umidade",
    wind: "Vento",
    precipitation: "Precipitação",
    detailsLabel: "Detalhes do tempo atual",
    forecastTitle: "Previsão de 10 dias",
    forecastLabel: "Previsão do tempo para dez dias",
    secureBroker: "Conexão de rede segura do Redeven",
    today: "Hoje",
    tonight: "Esta noite",
    high: "Máx.",
    low: "Mín.",
    poweredBy: "Dados meteorológicos: Open-Meteo.com · CC BY 4.0",
    searching: "Buscando locais…",
    noResults: "Nenhum local encontrado.",
    loading: "Carregando o tempo…",
    loadingLocation: "Carregando o tempo de {city}…",
    onboardingTitle: "Escolha uma cidade",
    onboardingBody:
      "Busque um local ou escolha uma cidade para ver a hora local, o tempo atual e a previsão de dez dias.",
    refreshFailed:
      "Exibindo o tempo salvo. A última atualização não está disponível.",
    permission:
      "O tempo em tempo real exige permissão de rede. Conceda a permissão e tente novamente.",
    unavailable:
      "O tempo em tempo real não está disponível. Seus locais recentes continuam disponíveis.",
    searchError: "A busca de locais não está disponível.",
    conditions: {
      "clear-day": "Céu limpo",
      "clear-night": "Céu limpo",
      "partly-cloudy": "Parcialmente nublado",
      cloudy: "Nublado",
      fog: "Nevoeiro",
      drizzle: "Garoa",
      rain: "Chuva",
      snow: "Neve",
      storm: "Trovoada",
      unknown: "Condições indisponíveis",
    },
    weather: "Tempo",
    hideSidebar: "Ocultar barra lateral",
    toggleSidebar: "Alternar barra lateral",
    savedWeather: "Previsão salva",
    observed: "Observação",
    hourly: "Previsão por hora",
    now: "Agora",
    daysForecast: "Previsão de {count} dias",
    gusts: "Rajadas de {speed}",
    actualTemperature: "Temperatura real: {temperature}",
    currentWind: "Velocidade atual do vento",
    relativeHumidity: "Umidade relativa",
    sunset: "Pôr do sol",
    sunrise: "Nascer do sol",
    precipitationTotal: "Precipitação",
    chanceToday: "Hoje · Chance de chuva: {chance}",
    uv: "Índice UV",
    lowUV: "Baixo",
    moderateUV: "Moderado",
    highUV: "Alto",
    veryHighUV: "Muito alto",
    visibility: "Visibilidade",
    horizontalVisibility: "Visibilidade horizontal",
    pressure: "Pressão",
    seaLevel: "hPa · Ao nível do mar",
    north: "N",
    west: "O",
    east: "L",
    south: "S",
    conditionsTitle: "Condições do tempo",
    closeDetails: "Fechar detalhes",
    dailyRange: "Faixa diária",
    missingHours:
      "Os detalhes por hora desta previsão salva não estão disponíveis. Atualize para tentar novamente.",
    temperatureType: "Tipo de temperatura",
    actual: "Real",
    millimeters: "mm",
    kilometers: "km",
    windUnit: "km/h",
  },
  "ru-RU": {
    chooseLocation: "Выбрать город",
    majorCities: "Крупные города",
    closeLocationPicker: "Закрыть выбор города",
    searchPlaceholder: "Поиск города или места",
    search: "Найти",
    searchHint:
      "Найдите город, чтобы увидеть местное время и прогноз на десять дней.",
    favorites: "Недавние места",
    remove: "Удалить",
    refresh: "Обновить",
    refreshing: "Обновление…",
    feelsLike: "Ощущается",
    humidity: "Влажность",
    wind: "Ветер",
    precipitation: "Осадки",
    detailsLabel: "Текущие погодные условия",
    forecastTitle: "Прогноз на 10 дней",
    forecastLabel: "Прогноз погоды на десять дней",
    secureBroker: "Безопасное сетевое подключение Redeven",
    today: "Сегодня",
    tonight: "Сегодня ночью",
    high: "Макс.",
    low: "Мин.",
    poweredBy: "Данные о погоде: Open-Meteo.com · CC BY 4.0",
    searching: "Поиск мест…",
    noResults: "Подходящие места не найдены.",
    loading: "Загрузка погоды…",
    loadingLocation: "Загрузка погоды: {city}…",
    onboardingTitle: "Выберите город",
    onboardingBody:
      "Найдите место или выберите город, чтобы увидеть местное время, текущую погоду и прогноз на десять дней.",
    refreshFailed:
      "Показана сохранённая погода. Последнее обновление недоступно.",
    permission:
      "Для актуальной погоды нужен доступ к сети. Предоставьте разрешение и повторите попытку.",
    unavailable:
      "Актуальная погода недоступна. Недавние места по-прежнему доступны.",
    searchError: "Поиск мест сейчас недоступен.",
    conditions: {
      "clear-day": "Ясно",
      "clear-night": "Ясно",
      "partly-cloudy": "Переменная облачность",
      cloudy: "Облачно",
      fog: "Туман",
      drizzle: "Морось",
      rain: "Дождь",
      snow: "Снег",
      storm: "Гроза",
      unknown: "Нет данных о погоде",
    },
    weather: "Погода",
    hideSidebar: "Скрыть боковую панель",
    toggleSidebar: "Показать или скрыть боковую панель",
    savedWeather: "Сохранённый прогноз",
    observed: "Наблюдение",
    hourly: "Почасовой прогноз",
    now: "Сейчас",
    daysForecast: "Прогноз на {count} дн.",
    gusts: "Порывы {speed}",
    actualTemperature: "Фактическая температура: {temperature}",
    currentWind: "Текущая скорость ветра",
    relativeHumidity: "Относительная влажность",
    sunset: "Закат",
    sunrise: "Восход",
    precipitationTotal: "Осадки",
    chanceToday: "Сегодня · Вероятность дождя: {chance}",
    uv: "УФ-индекс",
    lowUV: "Низкий",
    moderateUV: "Умеренный",
    highUV: "Высокий",
    veryHighUV: "Очень высокий",
    visibility: "Видимость",
    horizontalVisibility: "Горизонтальная видимость",
    pressure: "Давление",
    seaLevel: "гПа · На уровне моря",
    north: "С",
    west: "З",
    east: "В",
    south: "Ю",
    conditionsTitle: "Погодные условия",
    closeDetails: "Закрыть подробности",
    dailyRange: "Диапазон за день",
    missingHours:
      "Для сохранённого прогноза нет почасовых данных. Обновите прогноз и повторите попытку.",
    temperatureType: "Тип температуры",
    actual: "Фактическая",
    millimeters: "мм",
    kilometers: "км",
    windUnit: "км/ч",
  },
} as const;

export type WeatherTranslations = {
  [K in keyof (typeof translations)["en-US"]]: K extends "conditions"
    ? Record<WeatherConditionKind, string>
    : string;
};
export type WeatherMessageKey = Exclude<
  keyof WeatherTranslations,
  "conditions"
>;
export function localeForLanguageTag(
  languageTag: string | undefined,
): SupportedLocale {
  const parts = (languageTag ?? "en")
    .toLowerCase()
    .replaceAll("_", "-")
    .split("-");
  if (parts[0] === "zh") {
    if (parts.includes("hans")) return "zh-CN";
    return parts.some((part) => ["hant", "tw", "hk", "mo"].includes(part))
      ? "zh-TW"
      : "zh-CN";
  }
  return (
    supportedLocales.find(
      (locale) => locale.toLowerCase().split("-")[0] === parts[0],
    ) ?? "en-US"
  );
}
export function translationsForLocale(
  locale: SupportedLocale,
): WeatherTranslations {
  return translations[locale];
}
export function formatMessage(
  locale: SupportedLocale,
  key: WeatherMessageKey,
  values: Record<string, string | number> = {},
): string {
  let text: string = translations[locale][key];
  for (const [name, value] of Object.entries(values))
    text = text.replaceAll(`{${name}}`, String(value));
  return text;
}
export function formatCivilDate(
  value: string,
  locale: SupportedLocale,
  weekdayOnly = false,
): string {
  const date = new Date(`${value}T12:00:00Z`);
  if (Number.isNaN(date.getTime())) return "—";
  return new Intl.DateTimeFormat(locale, {
    timeZone: "UTC",
    ...(weekdayOnly
      ? { weekday: "short" as const }
      : {
          year: "numeric" as const,
          month: "long" as const,
          day: "numeric" as const,
        }),
  }).format(date);
}
type MajorCityDefinition = Omit<
  MajorCityLocation,
  "name" | "admin1" | "country"
> & {
  en: Pick<MajorCityLocation, "name" | "admin1" | "country">;
  zh: Pick<MajorCityLocation, "name" | "admin1" | "country">;
};

const majorCityDefinitions: readonly MajorCityDefinition[] = [
  {
    id: "preset:beijing",
    latitude: 39.9042,
    longitude: 116.4074,
    timezone: "Asia/Shanghai",
    en: { name: "Beijing", admin1: "Beijing", country: "China" },
    zh: { name: "北京", admin1: "北京市", country: "中国" },
  },
  {
    id: "preset:tokyo",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    en: { name: "Tokyo", admin1: "Tokyo", country: "Japan" },
    zh: { name: "东京", admin1: "东京都", country: "日本" },
  },
  {
    id: "preset:singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: "Asia/Singapore",
    en: { name: "Singapore", admin1: "", country: "Singapore" },
    zh: { name: "新加坡", admin1: "", country: "新加坡" },
  },
  {
    id: "preset:dubai",
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: "Asia/Dubai",
    en: { name: "Dubai", admin1: "Dubai", country: "United Arab Emirates" },
    zh: { name: "迪拜", admin1: "迪拜酋长国", country: "阿联酋" },
  },
  {
    id: "preset:sydney",
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: "Australia/Sydney",
    en: { name: "Sydney", admin1: "New South Wales", country: "Australia" },
    zh: { name: "悉尼", admin1: "新南威尔士州", country: "澳大利亚" },
  },
  {
    id: "preset:london",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
    en: { name: "London", admin1: "England", country: "United Kingdom" },
    zh: { name: "伦敦", admin1: "英格兰", country: "英国" },
  },
  {
    id: "preset:paris",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    en: { name: "Paris", admin1: "Île-de-France", country: "France" },
    zh: { name: "巴黎", admin1: "法兰西岛大区", country: "法国" },
  },
  {
    id: "preset:cairo",
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: "Africa/Cairo",
    en: { name: "Cairo", admin1: "Cairo", country: "Egypt" },
    zh: { name: "开罗", admin1: "开罗省", country: "埃及" },
  },
  {
    id: "preset:cape-town",
    latitude: -33.9249,
    longitude: 18.4241,
    timezone: "Africa/Johannesburg",
    en: { name: "Cape Town", admin1: "Western Cape", country: "South Africa" },
    zh: { name: "开普敦", admin1: "西开普省", country: "南非" },
  },
  {
    id: "preset:new-york",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    en: { name: "New York", admin1: "New York", country: "United States" },
    zh: { name: "纽约", admin1: "纽约州", country: "美国" },
  },
  {
    id: "preset:los-angeles",
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: "America/Los_Angeles",
    en: { name: "Los Angeles", admin1: "California", country: "United States" },
    zh: { name: "洛杉矶", admin1: "加利福尼亚州", country: "美国" },
  },
  {
    id: "preset:sao-paulo",
    latitude: -23.5505,
    longitude: -46.6333,
    timezone: "America/Sao_Paulo",
    en: { name: "São Paulo", admin1: "São Paulo", country: "Brazil" },
    zh: { name: "圣保罗", admin1: "圣保罗州", country: "巴西" },
  },
] as const;

const cityNames: Partial<Record<SupportedLocale, readonly string[]>> = {
  "zh-TW": [
    "北京",
    "東京",
    "新加坡",
    "杜拜",
    "雪梨",
    "倫敦",
    "巴黎",
    "開羅",
    "開普敦",
    "紐約",
    "洛杉磯",
    "聖保羅",
  ],
  "ja-JP": [
    "北京",
    "東京",
    "シンガポール",
    "ドバイ",
    "シドニー",
    "ロンドン",
    "パリ",
    "カイロ",
    "ケープタウン",
    "ニューヨーク",
    "ロサンゼルス",
    "サンパウロ",
  ],
  "ko-KR": [
    "베이징",
    "도쿄",
    "싱가포르",
    "두바이",
    "시드니",
    "런던",
    "파리",
    "카이로",
    "케이프타운",
    "뉴욕",
    "로스앤젤레스",
    "상파울루",
  ],
  "de-DE": [
    "Peking",
    "Tokio",
    "Singapur",
    "Dubai",
    "Sydney",
    "London",
    "Paris",
    "Kairo",
    "Kapstadt",
    "New York",
    "Los Angeles",
    "São Paulo",
  ],
  "fr-FR": [
    "Pékin",
    "Tokyo",
    "Singapour",
    "Dubaï",
    "Sydney",
    "Londres",
    "Paris",
    "Le Caire",
    "Le Cap",
    "New York",
    "Los Angeles",
    "São Paulo",
  ],
  "es-ES": [
    "Pekín",
    "Tokio",
    "Singapur",
    "Dubái",
    "Sídney",
    "Londres",
    "París",
    "El Cairo",
    "Ciudad del Cabo",
    "Nueva York",
    "Los Ángeles",
    "São Paulo",
  ],
  "pt-BR": [
    "Pequim",
    "Tóquio",
    "Singapura",
    "Dubai",
    "Sydney",
    "Londres",
    "Paris",
    "Cairo",
    "Cidade do Cabo",
    "Nova York",
    "Los Angeles",
    "São Paulo",
  ],
  "ru-RU": [
    "Пекин",
    "Токио",
    "Сингапур",
    "Дубай",
    "Сидней",
    "Лондон",
    "Париж",
    "Каир",
    "Кейптаун",
    "Нью-Йорк",
    "Лос-Анджелес",
    "Сан-Паулу",
  ],
};

const countryCodes = [
  "CN",
  "JP",
  "SG",
  "AE",
  "AU",
  "GB",
  "FR",
  "EG",
  "ZA",
  "US",
  "US",
  "BR",
];
export function majorCitiesForLocale(
  locale: SupportedLocale,
): MajorCityLocation[] {
  const countries = new Intl.DisplayNames(locale, { type: "region" });
  return majorCityDefinitions.map(({ en, zh, ...location }, index) => ({
    ...location,
    ...(locale === "zh-CN"
      ? zh
      : locale === "en-US"
        ? en
        : {
            name: cityNames[locale]![index],
            admin1: "",
            country: countries.of(countryCodes[index]) ?? en.country,
          }),
  }));
}
export function localizedLocation(
  location: MajorCityLocation,
  locale: SupportedLocale,
): MajorCityLocation {
  return (
    majorCitiesForLocale(locale).find((city) => city.id === location.id) ??
    location
  );
}

export function conditionForCode(
  code: number,
  isDay: boolean,
): WeatherCondition {
  if (code === 0)
    return isDay
      ? { kind: "clear-day", symbol: "☀️", label: "Clear sky" }
      : { kind: "clear-night", symbol: "🌙", label: "Clear sky" };
  if (code === 1 || code === 2)
    return {
      kind: "partly-cloudy",
      symbol: isDay ? "🌤️" : "☁️",
      label: "Partly cloudy",
    };
  if (code === 3) return { kind: "cloudy", symbol: "☁️", label: "Cloudy" };
  if (code === 45 || code === 48)
    return { kind: "fog", symbol: "🌫️", label: "Fog" };
  if (code >= 51 && code <= 57)
    return { kind: "drizzle", symbol: "🌦️", label: "Drizzle" };
  if ((code >= 61 && code <= 67) || (code >= 80 && code <= 82))
    return { kind: "rain", symbol: "🌧️", label: "Rain" };
  if ((code >= 71 && code <= 77) || (code >= 85 && code <= 86))
    return { kind: "snow", symbol: "🌨️", label: "Snow" };
  if (code >= 95 && code <= 99)
    return { kind: "storm", symbol: "⛈️", label: "Thunderstorm" };
  return { kind: "unknown", symbol: "•", label: "Conditions unavailable" };
}

export function temperatureRangeClasses(
  days: readonly TemperatureDay[],
  day: TemperatureDay,
  currentTemperature?: number,
): TemperatureRangeClasses {
  const globalMinimum = Math.min(...days.map((value) => value.temperature_min));
  const globalMaximum = Math.max(...days.map((value) => value.temperature_max));
  const span = Math.max(1, globalMaximum - globalMinimum);
  const start = boundedStep((day.temperature_min - globalMinimum) / span);
  const end = boundedStep((day.temperature_max - globalMinimum) / span);
  const width = Math.max(1, end - start);
  const current =
    currentTemperature === undefined
      ? undefined
      : boundedStep((currentTemperature - globalMinimum) / span);
  return {
    startClass: `range-start-${start}`,
    widthClass: `range-width-${width}`,
    currentClass:
      current === undefined ? undefined : `current-position-${current}`,
  };
}

function boundedStep(value: number): number {
  return Math.max(0, Math.min(10, Math.round(value * 10)));
}
